

############################################
#
#   Lights On When Coming Home and House Empty
#     Action: Turn On inside_house_lights
#     Trigger: Beam sensor
#     Conditions: Not_home and after sunset-45m
#
############################################ 
- action:
  - data:
      entity_id: group.inside_house_lights
    service: light.turn_on
  - data:
      entity_id: group.inside_house_lights
    service: switch.turn_on
  - data:
      entity_id:
      - switch.ge_unknown_type5052_id3031_switch_2
    service: switch.turn_on
  - data:
      entity_id: group.outside_house_lights
    service: switch.turn_on
  - delay: 00:00:10
  - data:
      #Dim rec room high
      entity_id: script.1514064524159
    service: script.turn_on
  alias: Lights On When Coming Home and House Empty
  condition:
    condition: and
    conditions:
    - condition: state
      entity_id: group.bluetooth_presence
      state: not_home
    - after: sunset
      after_offset: -00:45:00
      condition: sun
  id: '1513377062497'
  trigger:
  - entity_id: binary_sensor.fortrezz_mimolite_wireless_interfacebridge_module_sensor
    from: 'off'
    platform: state
    to: 'on'

############################################
#
#   Away from Home
#     Action: Turn Off all house_lights
#     Trigger: Bluetooth presence not_home for 3 mins
#     Conditions: None
#
############################################ 
- action:
  - data:
      entity_id:
      - group.inside_house_lights
      - group.rec_room
    service: light.turn_off
  - data:
      entity_id: group.inside_house_lights
    service: switch.turn_off
  - data:
      entity_id:
      - switch.ge_unknown_type5052_id3031_switch_2
      - switch.leviton_unknown_type3601_id0001_switch
    service: switch.turn_off
  - delay: 00:00:05
  - data:
      entity_id: group.outside_house_lights
    service: switch.turn_off
  - data:
      entity_id: group.inside_house_lights
    service: switch.turn_off
  alias: Away From Home
  condition: []
  id: '1514061377826'
  trigger:
  - entity_id: group.bluetooth_presence
    from: home
    platform: state
    to: not_home

############################################
#
#   Set Theater On
#     Action: Turn On projector, screen, receiver
#     Trigger: Harmony Remote set to TV or XBox
#     Conditions: None
#
############################################ 
- action:
  - data:
      entity_id:
      - switch.projector
    service: switch.turn_on
  - data:
      entity_id: switch.projector_screen
    service: switch.turn_on
  - delay: 00:00:05
  - data:
      entity_id: switch.projector
    service: switch.turn_on
  alias: Set Theater On
  condition: []
  id: '1514148400717'
  trigger:
  - entity_id: sensor.theater
    from: PowerOff
    platform: state
    to: Watch Fios TV
  - entity_id: sensor.theater
    from: Office TV
    platform: state
    to: Watch Fios TV
  - entity_id: sensor.theater
    from: PowerOff
    platform: state
    to: Xbox One
  - entity_id: sensor.theater
    from: Office TV
    platform: state
    to: Xbox One

############################################
#
#   Set Theater Off
#     Action: Turn off projector, screen, receiver
#     Trigger: Harmony Remote set to PowerOff
#     Conditions: None
#
############################################ 
- action:
  - data:
      entity_id:
      - switch.ge_unknown_type5052_id3031_switch_2
    service: switch.turn_on
  - data:
      entity_id: remote.teller_harmony_hub
    service: remote.turn_off
  - data:
      entity_id:
      - switch.projector
    service: switch.turn_off
  - data:
      entity_id: switch.projector_screen
    service: switch.turn_off
  - delay: 00:00:02
  - data:
      entity_id: switch.projector
    service: switch.turn_off
  - delay: 00:02:00
  - data:
      entity_id:
      - switch.ge_unknown_type5052_id3031_switch_2
    service: switch.turn_off
  alias: Set Theater Off
  condition: []
  id: '1514148400718'
  trigger:
  - entity_id: sensor.theater
    from: Watch Fios TV
    platform: state
    to: PowerOff
  - entity_id: sensor.theater
    from: Xbox One
    platform: state
    to: PowerOff


############################################
#
#   Evening Lights On
#     Action: Turn on inside and outside house lights
#     Trigger: Local Motion On
#     Conditions: Sunset-1h to 9 PM
#
############################################ 
- action:
  - data:
      entity_id:
      - group.inside_house_lights
      - group.outside_house_lights
    service: switch.turn_on
  - data:
      entity_id: group.inside_house_lights
    service: light.turn_on
  - data:
      entity_id: script.1514064524159
    service: script.turn_on
  - delay: 00:00:02
  - data:
      entity_id:
      - group.inside_house_lights
      - group.outside_house_lights
    service: switch.turn_on
  alias: Evening Lights On
  condition:
  - condition: and
    conditions:
    - after: sunset
      after_offset: -01:00:00
      condition: sun
    - before: '22:00'
      condition: time
  id: '1514838378061'
  trigger:
  - entity_id: group.local_motion_sensing
    from: 'off'
    platform: state
    to: 'on'

############################################
#
#   Evening time lights off
#     Action: Turn off all lights 
#     Trigger: No motion for 60m from local motion sensors
#     Conditions: Sunset-45m - 11:30 PM
#
############################################ 
- action:
  - data:
      entity_id:
      - group.inside_house_lights
      - group.outside_house_lights
      - switch.ge_unknown_type5052_id3031_switch_2
    service: switch.turn_off
  - data:
      entity_id: group.inside_house_lights
    service: light.turn_off
  - delay: 00:00:2
  - data:
      entity_id:
      - group.inside_house_lights
      - group.outside_house_lights
      - switch.ge_unknown_type5052_id3031_switch_2
    service: switch.turn_off
  - data:
      entity_id: group.inside_house_lights
    service: light.turn_off
  alias: Evening Light Timer
  condition:
    condition: and
    conditions:
    - after: sunset
      after_offset: -00:45:00
      condition: sun
    - condition: time
      before: '23:30'
  id: '1515887964298'
  trigger:
  - entity_id: group.local_motion_sensing
    platform: state
    to: 'off'
    for:
      minutes: 60


############################################
#
#   Night Lights On (Theater On - TV)
#     Action: Turn on night lights 
#     Trigger: Local Motion On
#     Conditions: 11:30 PM - 7:30 AM & Theater Off
#
############################################ 
- action:
  - data:
      # under cabinet light
      entity_id: light.ge_unknown_type4944_id3130_level_2
    service: light.turn_on
  - data:
      #Rec Room dimmed low script
      entity_id: script.1514064152005
    service: script.turn_on
  alias: Night Lights On Theather On TV
  condition:
    condition: and
    conditions:
    - after: '23:30'
      before: '07:30'
      condition: time
    - condition: state
      entity_id: sensor.theater
      state: Watch Fios TV
  id: '1514838378062'
  trigger:
  - entity_id: group.local_motion_sensing
    from: 'off'
    platform: state
    to: 'on'

############################################
#
#   Night Lights On (Theater On - Xbox One)
#     Action: Turn on night lights 
#     Trigger: Local Motion On
#     Conditions: 11:30 PM - 7:30 AM & Theater Off
#
############################################ 
- action:
  - data:
      # under cabinet light
      entity_id: light.ge_unknown_type4944_id3130_level_2
    service: light.turn_on
  - data:
      #Rec Room dimmed low script
      entity_id: script.1514064152005
    service: script.turn_on
  alias: Night Lights On Theather On TV
  condition:
    condition: and
    conditions:
    - after: '23:30'
      before: '07:30'
      condition: time
    - condition: state
      entity_id: sensor.theater
      state: Xbox One
  id: '1514838378062'
  trigger:
  - entity_id: group.local_motion_sensing
    from: 'off'
    platform: state
    to: 'on'
############################################
#
#   Night Lights On (Theater Off)
#     Action: Turn on night lights 
#     Trigger: Local Motion On
#     Conditions: 11:30 PM - 7:30 AM & Theater Off
#
############################################ 
- action:
  - data:
      # theater light
      entity_id: switch.ge_unknown_type5052_id3031_switch_2
      entity_id: switch.ge_12727_inwall_smart_switch_toggle_switch_2
    service: switch.turn_on
  - data:
      # under cabinet light
      entity_id: light.ge_unknown_type4944_id3130_level_2
    service: light.turn_on
  - data:
      #Rec Room dimmed low script
      entity_id: script.1514064152005
    service: script.turn_on
  alias: Night Lights On Theather Off
  condition:
    condition: and
    conditions:
    - after: '23:30'
      before: '07:30'
      condition: time
    - condition: state
      entity_id: sensor.theater
      state: PowerOff
  id: '1514838378062'
  trigger:
  - entity_id: group.local_motion_sensing
    from: 'off'
    platform: state
    to: 'on'

############################################
#
#   Night time lights off
#     Action: Turn off all lights 
#     Trigger: No motion from local motion sensors
#     Conditions: 11:30 pm - 06:10 AM
#
############################################    
- action:
  - data:
      entity_id:
      - group.inside_house_lights
      - group.outside_house_lights
      - switch.ge_unknown_type5052_id3031_switch_2
    service: switch.turn_off
  - data:
      entity_id:
      - group.inside_house_lights
      - light.ge_unknown_type4944_id3130_level
    service: light.turn_off
  - delay: 00:00:2
  - data:
      entity_id:
      - group.inside_house_lights
      - group.outside_house_lights
      - switch.ge_unknown_type5052_id3031_switch_2
      - switch.leviton_unknown_type3601_id0001_switch
    service: switch.turn_off
  - data:
      entity_id:
      - group.inside_house_lights
      - light.ge_unknown_type4944_id3130_level
    service: light.turn_off
  alias: Night Light Timer
  condition:
  - after: '23:30'
    before: '06:10'
    condition: time
  id: '1515887964299'
  trigger:
  - entity_id: group.local_motion_sensing
    platform: state
    to: 'off'

############################################
#
#   Outside Lights off at Sunrise
#     Action: Outside Lights off at Sunrise 
#     Trigger: sunrise
#     Conditions: None
#
############################################ 
- action:
  - data:
      entity_id:
      - group.outside_house_lights
    service: switch.turn_off
  alias: Outside Lights Off at Sunrise
  condition: []
  id: '1515259897457'
  trigger:
  - event: sunrise
    platform: sun

############################################
#   Set Brightness from Webapp
#     Action: Set brightness to dimmable lights 
#     Trigger: Webapp brightness changes
#     Conditions: None
#
############################################ 
- action:
  - service: light.turn_on
    data_template:
      entity_id:
      - light.ge_unknown_type4944_id3130_level_2
      - light.ge_12729_3way_dimmer_switch_level
      - light.ge_unknown_type4944_id3130_level
      brightness: '{{ trigger.to_state.state | int }}'
  alias: Master Brightness Slider
  condition: []
  id: '1515270713952'
  trigger:
  - entity_id: input_number.master_brightness
    platform: state


############################################
#
#   Disable driveway alert to prevent false positives
#     Action: Disable driveway alert for 3 mins
#     Trigger: Driveway_alert from beam sensor
#     Conditions: None
#
############################################ 
- action:
  - delay: 00:00:05
  - data:
      entity_id: automation.driveway_alert
    service: automation.turn_off
  - delay: 00:03:00
  - data:
      entity_id: automation.driveway_alert
    service: automation.turn_on
  alias: Driveway Alert Exit Disable
  condition: []
  id: '1518372795162'
  trigger:
  - entity_id: automation.driveway_alert
    from: 'on'
    platform: state
    to: 'off'


############################################
#
#   Aeotec Wallmote single press turns inside_house_lights ON
#     Action: Turn on all lights 
#     Trigger: Wallmote button press
#     Conditions: none
#
############################################    
- id: '1538938743083'
  alias: Wallmote Lamps On
  trigger:
  - event_data:
      entity_id: zwave.aeotec_zw130_wallmote_quad
      scene_id: 1
      scene_data: 0
    event_type: zwave.scene_activated
    platform: event
  - event_data:
      entity_id: zwave.aeotec_zw130_wallmote_quad
      scene_id: 2
      scene_data: 0
    event_type: zwave.scene_activated
    platform: event
  - event_data:
      entity_id: zwave.aeotec_zw130_wallmote_quad
      scene_id: 3
      scene_data: 0
    event_type: zwave.scene_activated
    platform: event
  - event_data:
      entity_id: zwave.aeotec_zw130_wallmote_quad
      scene_id: 4
      scene_data: 0
    event_type: zwave.scene_activated
    platform: event
  condition: []
  action:
  - data:
      entity_id:
      - group.inside_house_lights
    service: switch.turn_on
  - data:
      entity_id:
      - group.inside_house_lights
    service: light.turn_on

############################################
#
#   Aeotec Wallmote long press turns inside_house_lights OFF
#     Action: Turn off inside_house_lights group 
#     Trigger: Wallmote button long press
#     Conditions: none
#
############################################    
- id: '1538938743084'
  alias: Wallmote Lamps Off
  trigger:
  - event_data:
      entity_id: zwave.aeotec_zw130_wallmote_quad
      scene_id: 1
      scene_data: 1
    event_type: zwave.scene_activated
    platform: event
  - event_data:
      entity_id: zwave.aeotec_zw130_wallmote_quad
      scene_id: 2
      scene_data: 1
    event_type: zwave.scene_activated
    platform: event
  - event_data:
      entity_id: zwave.aeotec_zw130_wallmote_quad
      scene_id: 3
      scene_data: 1
    event_type: zwave.scene_activated
    platform: event
  - event_data:
      entity_id: zwave.aeotec_zw130_wallmote_quad
      scene_id: 4
      scene_data: 1
    event_type: zwave.scene_activated
    platform: event
  condition: []
  action:
  - data:
      entity_id:
      - group.inside_house_lights
    service: switch.turn_off
  - data:
      entity_id:
      - group.inside_house_lights
    service: light.turn_off

############################################
#
#   Sync Barn flood light with West Flood light
#     Action: Barn Big Flood On 
#     Trigger: West Flood On
#     Conditions: none
#
############################################ 
- id: '1538953465766'
  alias: Driveway Light Sync
  trigger:
  - entity_id: switch.ge_unknown_type4952_id3037_switch
    from: 'off'
    platform: state
    to: 'on'
  condition: []
  action:
  - data:
      entity_id: switch.ge_unknown_type4952_id3037_switch_3
    service: switch.turn_on


############################################
#
#   Driveway Alert
#     Action: Blink lights, IFTT alert, announce TTS google
#     Trigger: Beam sensor
#     Conditions: Home
#
############################################ 
- action:
  # - data:
        # Blink theater light
  #     entity_id: script.1512866664337
  #   service: script.turn_on
  - data:
      event: Driveway_Alert
    service: ifttt.trigger
  # - service: tts.google_say
  #   entity_id: media_player.kitchen_speaker
  #   data_template:
  #     message: '''{{ ["Looks like someone''s here. ", "Ding Dong. ", "Look alive.
  #       ", "Someone might be here. "] | random }}'' '
  alias: Driveway Alert
  condition:
  - condition: state
    entity_id: group.bluetooth_presence
    state: home
  id: '1512961411263'
  trigger:
  - entity_id: binary_sensor.fortrezz_mimolite_wireless_interfacebridge_module_sensor
    from: 'off'
    platform: state
    to: 'on'